# PARA ARMAR LOS CNTENEDORES CON IMAGEN DESDE DOCKER HUB
services:
  api:
    image: 10.51.15.42:5000/candidatos-api:latest
    container_name: candidatos-api
    ports:
      - 3008:3000
    restart: always
    networks:
      - candidatos-net
  app:
    image: 10.51.15.42:5000/candidatos-ui:latest
    container_name: candidatos-ui
    ports:
      - 8570:80
    restart: always
    depends_on:
      - api
    networks:
      - candidatos-net
    environment:
      API_URL: 'http://10.51.15.41:3008/'
      API_URL_USER: 'http://10.51.15.41:3001/'
      REPORTS_URL: 'http://10.51.15.110:8123/api/reports/'
      API_PADRON: 'http://10.51.15.41:3002/'
networks:
  candidatos-net:
    driver: bridge
    name: candidatos-net
